[package]
name = "libakuma"
version = "0.1.0"
edition = "2021"

[features]
default = []
chunked-allocator = []

[dependencies]
talc = "4"
embedded-io-async = { version = "0.6", default-features = false }