[package]
name = "paws"
version = "0.1.0"
edition = "2021"

[dependencies]
libakuma = { path = "../libakuma" }
noshell = { version = "0.3.0", features = ["parser"] }
# Future dependencies
# shlex = { version = "1.3.0", default-features = false }
