[package]
name = "sqld"
version = "0.1.0"
edition = "2021"

[lib]
name = "sqld"
path = "src/lib.rs"

[[bin]]
name = "sqld"
path = "src/main.rs"

[dependencies]
libakuma = { path = "../libakuma" }

[build-dependencies]
cc = "1.0"
