[package]
name = "box"
version = "0.1.0"
edition = "2021"

[dependencies]
libakuma = { path = "../libakuma" }
alloc = { version = "1.0.0", optional = true }

[[bin]]
name = "box"
path = "src/main.rs"
