[package]
name = "allocstress"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "allocstress"
path = "src/main.rs"

[dependencies]
libakuma = { path = "../libakuma", features = ["chunked-allocator"] }
