[workspace]
resolver = "2"
members = [
    "libakuma",
    "echo2",
    "elftest",
    "hello",
    "httpd",
    "stackstress",
    "stdcheck",
    "wget",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"

