[workspace]
resolver = "2"
members = [
    "libakuma",
    "echo2",
    "elftest",
    "hello",
    "stdcheck",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"

