[workspace]
resolver = "2"
members = [
    "libakuma",
    "libakuma-tls",
    "chainlink",
    "doom",
    "echo2",
    "elftest",
    "hello",
    "herd",
    "httpd",
    "meow",
    "quickjs",
    "scratch",
    "sqld",
    "stackstress",
    "stdcheck",
    "wget",
    "termtest",
    "allocstress"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"

